---
###
### Get the common python module packaged
###
- name: Remove the virtualenv
  file: path=/opt/helion-addins/pyapi/{{ common_pkg_role }}/.venv state=absent
  tags:
    - upgrade
    - install

- name: Create a venv to use
  command: virtualenv .venv
  args:
    chdir: "/opt/helion-addins/pyapi/{{ common_pkg_role }}/"
    creates: "/opt/helion-addins/pyapi/{{ common_pkg_role }}/.venv"
  tags:
    - upgrade
    - install

- name: Package the web app
  command: .venv/bin/python setup.py sdist
  args:
    chdir: "/opt/helion-addins/pyapi/{{ common_pkg_role }}/"
    creates: "/opt/helion-addins/pyapi/{{ common_pkg_role }}/dist/"
  tags:
    - upgrade
    - install
